In [58]:
import numpy as np 
import os 

array = np.array([[2,4,5,6], [6,7,8,9]])
filter = array < 5
print('filter sampple', filter)

filter sampple [[ True  True False False]
 [False False False False]]


In [65]:
import numpy as np
import os

destino = "../olis_sells/data/raw"
file_name = "olist_order_payments_dataset.csv"
borrame = os.path.join(destino, "ollis_order_payments_dataset.csv")
print("borrame", borrame)

np_original_array = np.genfromtxt(os.path.join(destino, file_name), delimiter=",")
print(np_original_array)

borrame ../olis_sells/data/raw/ollis_order_payments_dataset.csv
[[   nan    nan    nan    nan    nan]
 [   nan   1.      nan   8.    99.33]
 [   nan   1.      nan   1.    24.39]
 ...
 [   nan   1.      nan   1.    47.77]
 [   nan   1.      nan   5.   369.54]
 [   nan   1.      nan   1.   191.58]]


In [74]:
# Lets sum 2's into every entry of our original array
original_array = np_original_array
# print('original_array', original_array)

# Limpiar el arreglo para eliminar los nan
cleaned_arr = np.isfinite(original_array)
cleaned_arr_shape = cleaned_arr.shape
print('cleaned_array_shape', cleaned_arr_shape)

# Filtrar el arreglo original con np.where
filtered_array = np.where(np.isnan(original_array), 0, original_array)
print('fitlered_arr', filtered_array)
print('filtered_array', filtered_array)

# Les create a new array with 2's and add it to the original
new_array = np.ones(cleaned_arr_shape)*2

added_array = np.add(original_array, array_with_twos)
print('added array', added_array)

cleaned_array_shape (103887, 5)
fitlered_arr [[  0.     0.     0.     0.     0.  ]
 [  0.     1.     0.     8.    99.33]
 [  0.     1.     0.     1.    24.39]
 ...
 [  0.     1.     0.     1.    47.77]
 [  0.     1.     0.     5.   369.54]
 [  0.     1.     0.     1.   191.58]]
filtered_array [[  0.     0.     0.     0.     0.  ]
 [  0.     1.     0.     8.    99.33]
 [  0.     1.     0.     1.    24.39]
 ...
 [  0.     1.     0.     1.    47.77]
 [  0.     1.     0.     5.   369.54]
 [  0.     1.     0.     1.   191.58]]
added array [[   nan    nan    nan    nan    nan]
 [   nan   3.      nan  10.   101.33]
 [   nan   3.      nan   3.    26.39]
 ...
 [   nan   3.      nan   3.    49.77]
 [   nan   3.      nan   7.   371.54]
 [   nan   3.      nan   3.   193.58]]
